#! /bin/sh

xrdb ~/.Xresources
compton &
polybar top &
feh --bg-fill --no-xinerama .wallpaper.png
sxhkd &

bspc config window_gap    15
bspc config border_width  3
bspc config normal_border_color "#FFFFFF"
bspc config active_border_color "#FFFFFF"
bspc config focused_border_color "#AAAAFF"

bspc config split_ratio           0.50
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_by_distance     true
bspc config history_aware_focus   true
bspc config focus_follows_pointer true

bspc config pointer_action1 move
bspc config pointer_action3 resize_corner

bspc monitor HDMI-0  -d a1 a2 
bspc monitor DP-1    -d b1 b2
bspc monitor DP-3    -d c1 c2
bspc monitor DP-4    -d d1 d2

bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
