#! /bin/sh

xrdb ~/.Xresources
compton &
polybar main &
feh --bg-fill .wallpaper.jpg
sxhkd &

bspc config window_gap    0
bspc config border_width  2
bspc config normal_border_color  "#000000"
bspc config active_border_color  "#000000"
bspc config focused_border_color "#99cc99"

bspc config split_ratio           0.50
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_by_distance     true
bspc config history_aware_focus   true
bspc config focus_follows_pointer true

bspc config pointer_action1 move
bspc config pointer_action3 resize_corner

bspc monitor HDMI-0  -d a1 a2 a3 a4
bspc monitor DP-1    -d b1 b2
bspc monitor DP-3    -d c1 c2
bspc monitor DP-4    -d d1 d2
